### ISSUE TITLE
How to set value to 0 instead of 50 ?

### ISSUE THREAD

**Issue by MrShaikh1357** [ruisoftware/jquery-rsSliderLens#10]
Thank you for the nice plugin!

Can you help me out with how to set the value to 0. Now it starts with 50.

**Comment by ruisoftware** [comment]
Hi!

Thanks for the feedback and interest.

You can either set the value programatically (*) in the plugin constructor or in the html markup itself, which is the preferred way.

```html
<input id="i0" type="range" min="-20" max="50" value="0" step="10">
```

You can see a live example on CodePen [here](https://codepen.io/ruisoftware/pen/VwmLGZj?editors=1111)

(*) **Bug fix: Setting the value programatically was not working in 1.0.5 for input range controls. This has been fixed in 1.0.6. Thanks lot for finding this bug.**
