### ISSUE TITLE
Programatically update ruler values

### ISSUE THREAD

**Issue by rgvieira** [ruisoftware/jquery-rsSliderLens#7]
Jose Rui Santos

Please, trying to update ruler values array.

lista = [0,1,2,3,4,5,6,7,8)

- $(".myClass").rsSliderLens('option','ruler["labels"]["values"]',lista ) => not working
- $(".myClass").rsSliderLens('option','ruler.labels.values',lista ) => not working
- $(".myClass").rsSliderLens('option','ruler', {labels: {values:lista}} ) => not working
-  $(".myClass").rsSliderLens('option','ruler.labels', { values: lista }) => not working
-  $(".myClass").rsSliderLens('option','ruler','labels', { values: lista }) => not working
-  $(".myClass").rsSliderLens('option','ruler',{labels: { values: lista }})=> not working
-  $(".myClass").rsSliderLens('option',{ruler: {labels: { values: lista }}})=> not working

How can i code the rigth way?

**Comment by rgvieira** [comment]
Also, rsSliderLens('option', 'max', 200) does not work. 
But
rsSliderLens('option', 'value', 0) is ok.

**Comment by ruisoftware** [comment]
Currently, the getter/setter method `option` only supports the properties `enabled`, `value` and `range`.
It is my plan to allow to get and set more properties in future versions.

But for now, there is a valid workaround, which is to destroy the current plug-in instance and create another one with the desired configuration. This is so fast, that produces no noticeable flickering on the page.

## Update the max property
If your `$slider` plug-in was created with a maximum of 100
```html
     <input id="mySlider" type="range">
```` 
```javascript
var $slider = $("#mySlider")
               .rsSliderLens({ step: 25, paddingStart: 0.1, paddingEnd: 0.1, max: 100 });
```
![image](https://user-images.githubusercontent.com/428736/59348949-25418980-8d21-11e9-8318-56335f24f6ea.png)


you can _update_ the `max` property to 200 by
```javascript
$slider
   .rsSliderLens('destroy')                                                   // destroying the old instance
   .rsSliderLens({ step: 25, paddingStart: 0.1, paddingEnd: 0.1, max: 200 }); // and creating a new instance with max: 200
```
which renders as
![image](https://user-images.githubusercontent.com/428736/59349075-6df94280-8d21-11e9-8d87-94d1cbf9b3e7.png)
You might need to adjust the width or step to avoid the labels overlap each other.

## Update the labels on the ruler
Consider the same `$slider` instance from previous example, with a `max` of 100 and `step` 25, that displays the labels 0, 25, 50, 75 and 100.
To instead display the labels to 0, 1, 2, 3, 4, 5, 6, 7 and 8 there are basically two ways:
```javascript
$slider
   .rsSliderLens('destroy')
   .rsSliderLens({
      step: 25,
      paddingStart: 0.1,
      paddingEnd: 0.1,
      ruler: {
         labels: {
            values: [0,1,2,3,4,5,6,7,8]
         }
      }
   });
```
which in this case, understandably renders awfully as
![image](https://user-images.githubusercontent.com/428736/59350219-3c35ab00-8d24-11e9-955c-a120e9de03a6.png)
because, the plug-in is displaying the labels from 0 to 8 on a slider that ranges from 0 to 100. Therefore the labels appear all cramped in the beginning.

A better alternative would be to 
```javascript
$slider
   .rsSliderLens('destroy')
   .rsSliderLens({
      min: 0,     
      step: 1,
      max: 8,
      paddingStart: 0.1,
      paddingEnd: 0.1
   });
```
![image](https://user-images.githubusercontent.com/428736/59350528-fd542500-8d24-11e9-9380-24d16ed3a0df.png)

**Comment by ruisoftware** [comment]
Please note that you should update to the latest version 1.0.5, in order for the `destroy` method work correctly.

**Comment by rgvieira** [comment]
Thank you very much.

Now it´s working!!
