### ISSUE TITLE
Issues with BIG numbers such as UNIX Timestamps

### ISSUE THREAD

**Issue by smileBeda** [ruisoftware/jquery-rsSliderLens#9]
There is an issue when using `min` and `max` values exceeding a certain amount of cyphers.

1. Starting around value `1000000` the dragging becomes unusable, totally slow, "delayed". I assume there are too many steps to "process" when we go by step `1`.

2. While above could however be workarounded, the next related issue is showstopping. Example, `min: 10, max:100000000` will throw an error and break the plugin:
```
jquery.rsSliderLens.js:1210 Uncaught RangeError: Invalid string length
    at t (jquery.rsSliderLens.js:1210)
    at jquery.rsSliderLens.js:1241
    at Object.renderSvg (jquery.rsSliderLens.js:1250)
    at Object.initSvgOutsideHandle (jquery.rsSliderLens.js:26)
    at Object.initSvgHandle (jquery.rsSliderLens.js:290)
    at Object.init (jquery.rsSliderLens.js:305)
    at new a (jquery.rsSliderLens.js:1715)
    at HTMLInputElement.<anonymous> (jquery.rsSliderLens.js:1857)
    at Function.each (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.each (jquery.min.js?ver=3.5.1:2)
```

Again, it is obvious we cannot print out one million labels and steps on the slider, but these high numbers are nothing when we work with UNIX Timestamp, for which I intended to use your very nice JS Slider Plugin.

I want to produce a "Date" Slider where we can select a minimum and maximum date within a range of dates spanning from 1.1.2016 to 1.1.2021
That is already enough to break the plugin as it means to pass timestamp in seconds as  so:
```
var start = 946684800001;
var end   = Date.now();`
```

This breaks the plugin with above error message.
Even if we would divide above UNIX to make the number smaller, the amount of cyphers in the string is too much, and the plugin fails.

Is there any suggestion to create such Date Sliders with your plugin?
Perhaps I miss something obvious.

For reference, this is a sample code to replicate the issue:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery.rsSliderLens@1.0.5/test/sliderLens.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery.rsSliderLens@1.0.5/dist/jquery.rsSliderLens.min.js"></script>
<input type="range" id="full-custom-range">
<style>
body {
    background-color: unset !important;
}
</style>
<script>
var start = 946684800001;//begin 2016
var end   = Date.now();//today
jQuery("#full-custom-range").rsSliderLens({
	width: 369,
        min: start,
        max: end,
        value: [start, end],
		step: 2419200,//approximately one month in UNIX
		paddingStart: 0.1,
        paddingEnd: 0.1
});
</script>

**Comment by ruisoftware** [comment]
Hi!

Thanks for your interest in my plugin! Feedback like yours is much appreciated.

As you pointed out, the reason for this problem is the enormous length of the SVG ruler that the plugin needs to render. There are, however a few workarounds that I will try to demonstrate in a few steps that hopefully will lead us to a final solution.

### 1. Reconsider your min, max and step parameters.
The first point to consider, is that your `step` should be 1 day, as you want to display dates as days between Jan 1st 2016 and today's date. I suggest to use `min: 0` (representing Jan 1st 2016) and `max: 1836` (the elapsed days since Jan 1st 2016 until today).  
```javascript
<input type="range" id="full-custom-range">
<label id="label"></label>
<script>
        var getDateDiffInDays = function (fromDate, toDate) {
                return Math.floor((toDate - fromDate)/(24*60*60*1000));
            },
            from2016 = new Date(2016, 0, 1), // month is a 0 based index parameter (0 for January)
            toToday  = Date.now(),
            diff     = getDateDiffInDays(from2016, toToday);

        jQuery("#full-custom-range").rsSliderLens({
            width: 369,
            min: 0,
            max: diff,
            step: 1,
            onChange: function (event, value, isFirstHandle) {
                var date = new Date(from2016);
                date.setDate(date.getDate() + value);
                jQuery("#label").text(date.toLocaleDateString() + ' [' + value + ']');
            }
        });
</script>
```
As you see, this works but does not look pretty. The 1836 tick marks are cramped together in a tight space of only 369 pixels (see `width` parameter) causing a solid bar to be drawn.
![image](https://user-images.githubusercontent.com/428736/104120519-935c9100-5348-11eb-8126-df1cdd33ae0e.png)



### 2. Use a fixed handle.
One way to let the ruler expand whatever it needs to expand to accommodate all the labels and tick marks, without actually changing the slider physical size is to use a fixed handle slider.
This means the slider is still 369 pixels wide, but with a ruler much longer underneath. In this case, 1000% larger than 369.
Just add the following parameters to the plugin:
```javascript
            fixedHandle: true,
            ruler: {
                size: 10 // 1000% wider than the width 369
            },
```
This renders the tick marks fine, but the labels sill overlap each other.
![image](https://user-images.githubusercontent.com/428736/104120746-58f3f380-534a-11eb-9918-a1bb0d20de9e.png)
A caveat of this type of fixed handle sliders, is that they don't work with double handlers.

### 3. Display fewer labels
Here we are assigning the result of the `generateLabels()` function to the `ruler.labels.values` property.
```javascript
    <input type="range" id="full-custom-range">
    <label id="label"></label>

    <script>
        var getDateDiffInDays = function (fromDate, toDate) {
                return Math.floor((toDate - fromDate)/(24*60*60*1000));
            },
            from2016 = new Date(2016, 0, 1), // month is a 0 based index parameter (0 for January)
            toToday  = Date.now(),
            diff     = getDateDiffInDays(from2016, toToday),
            generateLabels = function () {
                var labels = [0], // first label as min
                    initialDate = new Date(from2016);
                for (var i = 0; i <= diff; ++i) {
                    var date = new Date(initialDate);
                    date.setDate(date.getDate() + i);
                    // label on every 1st day of every month
                    if (date.getDate() === 1) {
                        labels.push(i);
                    }
                }
                labels.push(diff); // last label as max
                return labels;
            };

        jQuery("#full-custom-range").rsSliderLens({
            width: 369,
            min: 0,
            max: diff,
            step: 1,
            fixedHandle: true,
            ruler: {
                size: 10, // 1000% wider than the width 369

                labels: {
                    values: generateLabels()
                }
            },
            onChange: function (event, value, isFirstHandle) {
                var date = new Date(from2016);
                date.setDate(date.getDate() + value);
                jQuery("#label").text(date.toLocaleDateString() + ' [' + value + ']');
            },
            paddingStart: 0.1,
            paddingEnd: 0.1
        });
    </script>
```
Which renders labels on the first day of every month.
![image](https://user-images.githubusercontent.com/428736/104121622-c2770080-5350-11eb-9ab1-b5fc5d3bca16.png)

It is clear that these are not the labels we wished for, since we are using a day range from 0 to today's date.
To display the proper dates, we need to somehow convert the day index to a concrete date. To accomplish this, use a a custom `ruler.labels.onCustomLabel` callback function.
```javascript
                    onCustomLabel: function (event, value) {
                        var date = new Date(from2016);
                        date.setDate(date.getDate() + value);
                        return date.toLocaleDateString(); 
                    }
```
which renders the correct labels. We can verify that the label 244 (244 days since 01/01/2016) corresponds to 01/09/2016.
![image](https://user-images.githubusercontent.com/428736/104121695-53e67280-5351-11eb-96e9-257ffb983e81.png)

### 4. Use a vertical layout to accommodate more labels 
If you want to display a date label not every month, but every 10 days, for example, then naturally the labels will start to overlap again.
To workaround this problem, simply add the parameter `orientation: 'vert'` for a vertical layout.
```javascript
    <input type="range" id="full-custom-range">
    <label id="label"></label>

    <script>
        var getDateDiffInDays = function (fromDate, toDate) {
                return Math.floor((toDate - fromDate)/(24*60*60*1000));
            },
            from2016 = new Date(2016, 0, 1), // month is a 0 based index parameter (0 for January)
            toToday  = Date.now(),
            diff     = getDateDiffInDays(from2016, toToday),
            generateLabels = function () {
                var labels = [0], // first label as min
                    initialDate = new Date(from2016);
                for (var i = 0; i <= diff; ++i) {
                    var date = new Date(initialDate);
                    date.setDate(date.getDate() + i);
                    // label every 10 days
                    if (date.getDate() % 10 === 0) {
                        labels.push(i);
                    }
                }
                labels.push(diff); // last label as max
                return labels;
            };

        jQuery("#full-custom-range").rsSliderLens({
            orientation: 'vert',
            width: 130,
            height: 300,
            min: 0,
            max: diff,
            step: 1,
            fixedHandle: true,
            ruler: {
                size: 10, // 1000% wider than the width 369

                labels: {
                    values: generateLabels(),
                    onCustomLabel: function (event, value) {
                        var date = new Date(from2016);
                        date.setDate(date.getDate() + value);
                        return date.toLocaleDateString(); 
                    },
                    pos: 0.65
                },
                tickMarks: {
                    short: {
                        pos: 0.3
                    },
                    long: {
                        pos: 0.25
                    }
                }
            },
            range: {
                pos: 0.42,
                size: 0.02
            },
            onChange: function (event, value, isFirstHandle) {
                var date = new Date(from2016);
                date.setDate(date.getDate() + value);
                jQuery("#label").text(date.toLocaleDateString() + ' [' + value + ']');
            },
            paddingStart: 0.1,
            paddingEnd: 0.1
        });
    </script>

```
![image](https://user-images.githubusercontent.com/428736/104122173-78901980-5354-11eb-9d1e-0e207cda794f.png)

### 5. Use a normal slider with two handlers
If the fixed handler is not for you, then you can use the normal style, with a label every year.
Here is how to implement a double handler slider.
```javascript
<style>
    .sliderlens .range > div {
        background-color: #d6d693;
    }
</style> 
<body>
    <input type="range" id="full-custom-range">
    <label id="label1"></label>
    <label id="label2"></label>

    <script>
        var getDateDiffInDays = function (fromDate, toDate) {
                return Math.floor((toDate - fromDate)/(24*60*60*1000));
            },
            from2016 = new Date(2016, 0, 1), // month is a 0 based index parameter (0 for January)
            toToday  = Date.now(),
            diff     = getDateDiffInDays(from2016, toToday),
            generateLabels = function () {
                var labels = [0], // first label as min
                    initialDate = new Date(from2016);
                for (var i = 0; i <= diff; ++i) {
                    var date = new Date(initialDate);
                    date.setDate(date.getDate() + i);
                    // label on every 1st day of every year
                    if (date.getDate() === 1 && date.getMonth() === 0) {
                        labels.push(i);
                    }
                }
                labels.push(diff); // last label as max
                return labels;
            };

        jQuery("#full-custom-range").rsSliderLens({
            width: 369,
            min: 0,
            max: diff,
            step: 1,
            value: [0, diff],
            ruler: {
                labels: {
                    values: generateLabels(),
                    onCustomLabel: function (event, value) {
                        var date = new Date(from2016);
                        date.setDate(date.getDate() + value);
                        return date.toLocaleDateString(); 
                    }
                },
                tickMarks: {
                    short: {
                        visible: false
                    },
                    long: {
                        step: 30 // a long tick mark every month
                    }
                }
            },
            range: {
                type: 'between' // not mandatory
            },
            onChange: function (event, value, isFirstHandle) {
                var date = new Date(from2016);
                date.setDate(date.getDate() + value);
                jQuery("#label" + (isFirstHandle? 1: 2)).text(date.toLocaleDateString() + ' [' + value + ']');
            },
            paddingStart: 0.1,
            paddingEnd: 0.1
        });
    </script>
```
![image](https://user-images.githubusercontent.com/428736/104122600-0bca4e80-5357-11eb-9de6-117a0ad85bdd.png)

### 6. Should you actually consider this plugin?
This slider plug-in was designed to ease the selection of values from a reasonably sized range. It becomes particularly hard 
 for the user to select a specific value from large ranges, as the granularity becomes very dense. This is especially true for the non fixed handle style, since it has to render the entire range in a finite length.
Another alternative would be to render 3 separated sliders, for the year, month and day.
Keyboard input is another important user experience topic. Although this plugin accepts <kbd>Home</kbd>, <kbd>End</kbd>, <kbd>PgUp</kbd>, <kbd>PgDown</kbd>, the mouse wheel, and the cursor keys for fine selection input, it does not accept numerical input.

I hope this will give you at least some useful info to solve your problem.

**Comment by smileBeda** [comment]
Hello!

This is amazing reference and hints. And you are right, it might not be the right tool for what I have in mind, in fact I switched to [ION RangeSlider](http://ionden.com/a/plugins/ion.rangeSlider/), which comes with a native Date Slide/Range selector, so it makes these things a bit easier.

But I definitely like your plugin, I think I will just have to use it for less "large" sets of data or better said, a definite set of data instead of an infinite (or almost infinite) set.

Even if I will go with ION on this particular project, the kind of reply above makes me want to use your plugin at all costs :)

Thanks!!
